# No xdg dir
export XDG_DESKTOP_DIR=/dev/null

# termial for mimeopen
export TERMINAL="/usr/bin/alacritty -e"

export DENO_INSTALL="$HOME/.deno"

# Support for android studio sdk and other craps
export ANDROID_STUDIO=/opt/android-studio
export ANDROID_HOME=/opt/android-sdk
export FLUTTER_HOME=/opt/flutter  
export PATH=/opt/flutter/.pub-cache/bin:/usr/local/go/bin:/usr/lib/dart/bin:$ANDROID_HOME/tools:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools:$ANDROID_STUDIO/tools:$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$HOME/.yarn/bin:$DENO_INSTALL/bin:$HOME/.cargo/bin:$HOME/.bin:/usr/local/bin::$HOME/.bin:/usr/local/bin::/usr/local/sbin:/usr/local/bin:/usr/bin:/bin::$PATH

# Longer passwords generated by password store
export PASSWORD_STORE_GENERATED_LENGTH=40

###############################
### Backend wayland support ###
###############################
# Better compatibility with java windows
export _JAVA_AWT_WM_NONREPARENTING=1

export CLUTTER_BACKEND=wayland

export WLC_USE_EGLDEVICE=1

#######################
### Keyboard config ###
#######################
# dead ' + c = ç
export GTK_IM_MODULE=cedilla
export QT_IM_MODULE=cedilla

#########################
### Defaults programs ###
#########################
# NeoVim is the best editor !!!!
export EDITOR="nvim"
# Setting up pager
export PAGER="less"
# Support for 256 colors in the term
export TERM="xterm-256color"
# Default browser depend on the display type
if [ -n "$DISPLAY" ]; then
    export BROWSER=qutebrowser
else 
    export BROWSER=links
fi

# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fdfind --type f'

# Compatibility with a lot of colors
export TERM=xterm-256color

# Ignore some command in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Bit Warden Session
export BW_SESSION="HCG8qrtm8GgSEwUg0XWjL172odOpiCLsi9u9oYPysr00AE8mmxJZuS6mOsJcFfK/+La1j/fbGyvaT8eOJHFtGg=="
