#!/bin/sh

cd "$HOME" || exit

system_version=$(uname -v | head -n1 | sed -e 's/\s.*$//' | sed 's/^[^-]*-//')

echo "Installing NeoVim"
if [ "$system_version" = "Ubuntu" ] || [ "$system_version" = "Microsoft" ]; then
	echo "Adding PPA for NeoVim unstable"
	sudo add-apt-repository -y ppa:neovim-ppa/unstable
	sudo apt -y update

	echo "Installing NeoVim"
	sudo apt -y install neovim

	echo "Installing NeoVim's depenencies"
	sudo apt -y install python-neovim
	sudo apt -y install python3-neovim

	curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
	echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
	sudo apt update
	sudo apt install yarn

	echo "Setting up environement"
	CUSTOM_NVIM_PATH=$(which nvim)
	set -u
	sudo update-alternatives --install /usr/bin/ex ex "${CUSTOM_NVIM_PATH}" 110
	sudo update-alternatives --install /usr/bin/vi vi "${CUSTOM_NVIM_PATH}" 110
	sudo update-alternatives --install /usr/bin/view view "${CUSTOM_NVIM_PATH}" 110
	sudo update-alternatives --install /usr/bin/vim vim "${CUSTOM_NVIM_PATH}" 110
	sudo update-alternatives --install /usr/bin/vimdiff vimdiff "${CUSTOM_NVIM_PATH}" 110
fi

echo "Installing zgen"
git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

echo "Installing qutebrowser"
if [ "$system_version" = "Ubuntu" ] || [ "$system_version" = "Debian" ]; then
	sudo apt install qutebrowser
fi
echo "Setting qutebrowser as default"
xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop