# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Importing library needed to get current path
import os, inspect

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Which cookies to accept.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain.
#   - never: Don't accept cookies at all.
c.content.cookies.accept = 'no-3rdparty'

# Store cookies. Note this option needs a restart with QtWebEngine on Qt
# < 5.9.
# Type: Bool
c.content.cookies.store = True

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Enable JavaScript.
# Type: Bool
c.content.javascript.enabled = False

# Openning list of domain where javascript is allowed
text_file = open(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))) + "/jsAllow.txt", "r")
# Creating a array from the file
domains = text_file.read().split('\n')
# Deleting last element as it is empty (and thus, allow javascript anywhere)
del domains[-1]

# Enable javascript on the allowed domains
for domain in domains:
    config.set('content.javascript.enabled', True, '*.' + domain)
text_file.close()


# Mode to use for hints.
# Type: String
# Valid values:
#   - number: Use numeric hints. (In this mode you can also type letters from the hinted element to filter and reduce the number of elements that are hinted.)
#   - letter: Use the characters in the `hints.chars` setting.
#   - word: Use hints words based on the html elements and the extra words.
c.hints.mode = 'number'

# Hide the statusbar unless a message is shown.
# Type: Bool
c.statusbar.hide = False

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = 'right'

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'switching'

# Width (in pixels or as percentage of the window) of the tab bar if
# it's vertical.
# Type: PercOrInt
c.tabs.width = '10%'

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'https://qwant.com'

# Search engines which can be used via the address bar. Maps a search
# engine name (such as `DEFAULT`, or `ddg`) to a URL with a `{}`
# placeholder. The placeholder will be replaced by the search term, use
# `{{` and `}}` for literal `{`/`}` signs. The search engine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {'DEFAULT': 'https://www.qwant.com/?l=en&h=0&hc=1&a=1&s=0&b=0&i=1&r=BE&sr=fr&q={}', 'acom': 'https://www.amazon.com/s/ref=nb_sb_noss?field-keywords={}', 'ade': 'https://www.amazon.de/s/ref=nb_sb_noss?field-keywords={}', 'aes': 'https://www.amazon.es/s/ref=nb_sb_noss?field-keywords={}', 'afr': 'https://www.amazon.fr/s/ref=nb_sb_noss?field-keywords={}', 'ait': 'https://www.amazon.it/s/ref=nb_sb_noss?field-keywords={}', 'auk': 'https://www.amazon.co.uk/s/ref=nb_sb_noss?field-keywords={}', 'aw': 'https://wiki.archlinux.org/?search={}', 'ddg': 'https://duckduckgo.com/?q={}', 'gg': 'https://www.google.com/search?q={}', 'wen': 'https://en.wikipedia.org/w/?search={}', 'wfr': 'https://fr.wikipedia.org/w/?search={}', 'yt': 'https://youtube.com/results?search_query={}', 'ebcom': 'https://www.ebay.com/sch/i.html?_nkw={}', 'ebbe': 'https://www.ebay.fr/sch/i.html?_nkw={}'}

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'https://qwant.com'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#333'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#222'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#0099cc'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = 'black'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = 'black'

# Bindings for normal mode
config.bind(',d', 'spawn youtube-dl -o ~/Videos/%(title)s.%(ext)s {url}')
config.bind(',m', 'spawn umpv {url}')
config.bind(';d', 'hint links spawn youtube-dl -o ~/Videos/%(title)s.%(ext)s {hint-url}')
config.bind(';m', 'hint links spawn umpv {hint-url}')
config.bind('E', 'spawn --userscript /home/toum/.scripts/qutepass.py -Y')
config.bind('e', 'spawn --userscript /home/toum/.scripts/qutepass.py --username xorob0')
config.bind('aa', 'spawn --userscript /home/toum/.scripts/jsAllow.py -a')
config.bind('au', 'spawn --userscript /home/toum/.scripts/jsAllow.py -d')
