[theme]
name = "slick"
[theme.overrides]
separator = "<span size='larger' font='12'>\uE0BA</span>"
idle_bg = "#2E3440"
idle_fg = "#ECEFF4"
info_bg = "#2E3440"
info_fg = "#B48EAD"
good_bg = "#2E3440"
good_fg = "#A3BE8C"
warning_bg = "#D08770"
warning_fg = "#eceff4"
critical_bg = "#BF616A"
critical_fg = "#eceff4"


[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 40

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = true
ip = true
speed_up = true
graph_up = false
interval = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"