# This is a basic workflow to help you get started with Actions

name: test-archlinux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: archlinux

    steps:
    - name: Intall yadm
      run: |
        curl https://raw.githubusercontent.com/TheLocehiliosan/yadm/master/yadm > yadm
        mv ./yadm /bin/yadm
        chmod +x /bin/yadm
 
    - name: Bootstrap yadm
      env:
        URL: ${{ github.repositoryUrl }}
      run: |
        yes | pacman -Sy
        yes | pacman -S git
        yadm clone $URL
        yadm bootstrap

    - name: Run test file
      run: bash $HOME/.config/yadm/test.sh
